esphome:
  name: sma-net-full
  friendly_name: "SMA Net Full"

external_components:
  - source:
      type: local
      path: ../components
    components: [sma_net]

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Fallback-SMA"
    password: !secret wifi_password

logger:
  level: DEBUG
  baud_rate: 0

api:

ota:
  - platform: esphome

captive_portal:

uart:
  id: uart_sma
  tx_pin: GPIO21
  rx_pin: GPIO20
  baud_rate: 19200
  stop_bits: 1
  parity: NONE

sma_net:
  id: sma
  uart_id: uart_sma
  update_interval: 3s
  slow_factor: 20
  debug: true

sensor:
  - platform: sma_net
    sma_net_id: sma
    channel: Pac
    interval: fast
    name: "Pac"
    icon: "mdi:flash"
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    accuracy_decimals: 0

  - platform: sma_net
    sma_net_id: sma
    channel: GridMs.PhV.phsA
    name: "Netzspannung L1"
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 2

  - platform: sma_net
    sma_net_id: sma
    channel: GridMs.A.phsA
    name: "Netzstrom L1"
    unit_of_measurement: "A"
    device_class: current
    state_class: measurement
    accuracy_decimals: 3

  - platform: sma_net
    sma_net_id: sma
    channel: GridMs.Hz
    name: "Netzfrequenz"
    unit_of_measurement: "Hz"
    device_class: frequency
    state_class: measurement
    accuracy_decimals: 2

  - platform: sma_net
    sma_net_id: sma
    channel: E-Total
    name: "Gesamtertrag"
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 3

text_sensor:
  - platform: sma_net
    sma_net_id: sma
    channel: "Data_Timestamp"
    name: "Zeitstempel Daten"
    entity_category: diagnostic

  - platform: sma_net
    sma_net_id: sma
    channel: "Mode"
    name: "Mode"

  - platform: sma_net
    sma_net_id: sma
    channel: "Error"
    name: "Error"
    entity_category: diagnostic
